/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.api.dsl.scoping

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 *
 */
class ApiDslScopeProvider extends de.jpaw.bonaparte.dsl.scoping.BonScriptScopeProvider {

}
