/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.api.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ApiDslUiModule extends de.jpaw.bonaparte.api.dsl.ui.AbstractApiDslUiModule {
    public ApiDslUiModule(AbstractUIPlugin plugin) {
        super(plugin);
    }
}
