/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.api.dsl.ui.contentassist

import de.jpaw.bonaparte.api.dsl.ui.contentassist.AbstractApiDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ApiDslProposalProvider extends AbstractApiDslProposalProvider {
}
