/*
 * generated by Xtext
 */
package de.jpaw.bonaparte.api.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ApiDslRuntimeModule extends de.jpaw.bonaparte.api.dsl.AbstractApiDslRuntimeModule {

}
